'use strict';
let payload=null, selected=null, token=null, busy=false, localPrepared=null;
const drafts=new Map();
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=v=>String(v??'').replaceAll('_',' ');
const date=v=>v?new Date(v*1000).toLocaleString():'Not started';
const duration=s=>s%3600===0?`${s/3600} hours`:`${Math.round(s/60)} minutes`;
function brief(value){
 const text=String(value||'');
 if(text.startsWith('Technical validation failed:'))return 'The proposed method failed technical validation.';
 if(/Traceback|\\Users\\|\/home\//.test(text))return 'The operation failed. The recorded error is available in the evidence details.';
 return text.length>200?text.slice(0,197)+'…':text;
}
function card(title,body){return `<section class="card"><h3>${esc(title)}</h3>${body}</section>`;}
function current(){return payload?.campaigns.find(c=>c.id===selected);}
function preferred(){return payload.campaigns.find(c=>['active','closing'].includes(c.status))?.id||localPrepared||payload.runtime.prepared_campaign||payload.campaigns[0]?.id;}
function render(){
 const open=new Set([...document.querySelectorAll('#overview details[open]')].map(e=>e.id));
 const runtime=payload.runtime||{}, campaigns=payload.campaigns||[];
 if(!campaigns.some(c=>c.id===selected))selected=preferred();
 $('#chooser').innerHTML=campaigns.map(c=>`<option value="${esc(c.id)}" ${c.id===selected?'selected':''}>${esc(c.objective)} · ${esc(label(c.status))} · ${esc(c.id.slice(0,8))}</option>`).join('');
 $('#empty').hidden=!!campaigns.length;$('#history-panel').hidden=campaigns.length<2;
 $('#runtime').innerHTML=`<p><strong>${runtime.ready?'Checks passed for a first bounded campaign.':'Launch checks need attention.'}</strong></p><p>${esc(runtime.explanation||'No runtime assessment recorded.')}</p>${[...(runtime.blockers||[]),...(runtime.limitations||[])].map(b=>`<p>${esc(b)}</p>`).join('')}`;
 const c=current();if(!c){$('#overview').innerHTML='';return;}
 const historical=c.id!==preferred(), unstarted=!c.sessions.length;
 const live=payload.live?.[c.id], work=live?.state, sample=work?.sample, research=payload.research?.[c.id];
 const active=c.jobs.find(j=>['dispatching','running','cancelling','unknown'].includes(j.state));
 const h=c.hypotheses.at(-1), conclusions=c.jobs.filter(j=>j.result);
 const incidents=(c.incidents||[]).filter(i=>!['resolved','task_abandoned'].includes(i.status));
 const accounting=incidents.filter(i=>i.category==='accounting');
 const attention=incidents.filter(i=>i.category!=='accounting');
 const status=c.campaign_status||{};
 const blockers=[...c.blockers.map(b=>brief(b.reason||label(b.kind))),...(!runtime.ready&&!historical&&c.status!=='active'?(runtime.blockers?.length?runtime.blockers:['Launch checks have not passed']):[])];
 const phases={plan:'Choosing a research question',implement:'Preparing a proposed method',prepare:'Checking the experiment package',review:'Independent method review',dispatch:'Starting the experiment',execute:'Running the experiment',assess:'Assessing the results',review_conclusion:'Independent conclusion review',investigate:'Investigating a plateau'};
 let heading,description,action='';
 if(historical){heading='Earlier campaign record';description='This view shows retained evidence. Return to the current campaign to launch or control research.';action='<button id="return-current" class="primary">Return to current campaign</button>';}
 else if(c.status==='closing'){heading='Stopping campaign';description='New work is blocked. Waiting for checkpointing, process termination and a final report.';action='<button id="stop">Stop requested</button>';}
 else if(status.state==='awaiting_decision'){heading='A human decision is needed';description=status.message; if(c.status==='active')action='<button id="stop">Stop campaign</button>';}
 else if(blockers.length){heading='Action needed before continuing';description='Research cannot proceed until the recorded issue is resolved. Inspect the details below.';if(c.status==='active')action='<button id="stop">Stop campaign</button>';}
 else if(c.status==='active'&&['recovering','waiting','awaiting_decision'].includes(status.state)){heading=label(status.state)+(status.retry_at?' until '+date(status.retry_at):'');description=status.message;action='<button id="stop">Stop campaign</button>';}
 else if(c.status==='active'){heading=phases[research?.phase]||'Campaign running';description='Continuing automatically. No action is needed from you.';action='<button id="stop">Stop campaign</button>';}
 else if(c.status==='authorized'){heading='Ready to start your research campaign';description='Nothing is running yet. Start the campaign to let the AI propose an experiment, obtain independent review, and run the game.';action='<button id="start" class="primary">Start campaign</button>';}
 else if(c.status==='draft'){heading='Review and authorize this campaign';description='Check the objective and limits below. Authorization records permission; you then choose when to start.';action='<button id="start" class="primary">Authorize campaign</button>';}
 else {heading='Campaign finished — review the results';description=c.summary?.next||'Read the findings and limitations before renewing. Renewal starts another authorized session.';action=c.eligibility?.resume_session?.allowed?'<button id="resume" class="primary">Resume remaining authorization</button>':c.eligibility?.renew?.allowed?'<button id="start" class="primary">Renew campaign</button>':'';description=status.message||description;}
 const facts=unstarted?`<div><span>Maximum duration</span><strong>${duration(c.policy.duration_seconds)} from Start</strong></div><div><span>Finish safely</span><strong>Last ${Math.round(c.policy.closeout_seconds/60)} minutes reserved</strong></div>`:`<div><span>Hard deadline</span><strong>${esc(date(c.deadline))}</strong></div><div><span>Experiments ended</span><strong>${c.jobs.filter(j=>['succeeded','failed','cancelled'].includes(j.state)).length}</strong></div>`;
 const hero=`<section class="card launch"><p class="eyebrow">${historical?'HISTORY':c.status==='active'?'IN PROGRESS':unstarted?'NEXT STEP':'CAMPAIGN STATUS'}</p><h2>${esc(heading)}</h2><p class="lead">${esc(brief(description))}</p><div class="launch-action">${action}${unstarted&&!historical?'<span>The timer begins when you press Start.</span>':''}</div><div class="objective"><span class="label">Objective</span><p>${esc(c.objective)}</p></div><div class="facts">${facts}<div><span>Research calls used</span><strong>${c.ai_executions?.length||0} / ${esc(c.policy.max_ai_invocations||24)}</strong></div></div>${blockers.length?`<details id="blocking-details" ${historical||attention.length?'':'open'}><summary>${blockers.length} recorded issue${blockers.length===1?'':'s'}</summary>${blockers.map(b=>`<p class="blocker">${esc(b)}</p>`).join('')}<p>Open the evidence for the affected operation and its required next action.</p></details>`:''}</section>`;
 const incidentCards=attention.length?card(attention.some(i=>i.status==='human_decision_required')?'Your decision is needed':'Automatic recovery',attention.map(i=>`<article class="entry"><strong>${esc(label(i.category))} · ${esc(label(i.status))}</strong><p>${esc(brief(i.reason))}</p>${i.category==='access'&&i.status==='human_decision_required'?'<button class="access-check">I restored access — verify</button>':''}${i.category==='task'?'<p>Repair attempts: '+esc(i.attempts||0)+' / '+esc(i.allowance||2)+'</p>':''}<p>${(()=>{const e=c.ai_executions?.find(e=>e.id===i.scope);return e?(e.termination_confirmed?'Process termination confirmed':'Process termination unconfirmed'):i.category==='termination'?'Process termination unconfirmed':'';})()}</p><p>${esc(i.category==='task'&&c.status!=='active'?'Recovery is deferred until the campaign is eligible to resume':i.next_action||'No automatic action scheduled')}${i.retry_at&&c.status==='active'?' · '+esc(date(i.retry_at)):''}</p><details id="incident-${esc(i.id)}"><summary>Evidence and clearance condition</summary><p>Affected work: ${esc(i.scope)}</p><pre>${esc(i.reason)}</pre><p>${esc(i.clearance)}</p><pre>${esc(JSON.stringify({facts:i.facts,evidence:i.evidence,blocked_operations:i.blocked_operations},null,2))}</pre></details></article>`).join('')):'';
 const agents=payload.agents?.[c.id];
 const team=agents?card('Research team',`<div class="agent-count"><strong>${agents.live} live agent${agents.live===1?'':'s'}</strong><span>up to ${agents.limit} simultaneous executions${agents.unconfirmed?` · ${agents.unconfirmed} awaiting process confirmation`:''}</span></div>${active&&!agents.live?'<p class="muted">The experiment is running; no AI call is active.</p>':''}<details id="agent-activity"><summary>Show agent activity and published explanations</summary><p class="muted">These are assigned tasks and public messages, not private internal reasoning. Messages appear when the agent publishes them; silent processing has no live thought transcript.</p>${['coordinator','worker','reviewer'].map(role=>{const rows=agents.executions.filter(e=>e.role===role).sort((a,b)=>b.started_at-a.started_at);const e=rows[0];return `<section class="agent-row"><h4>${esc(label(role))} <span class="status">${e?esc(label(e.status)):'idle'}</span></h4>${e?`<p>${esc(e.task)}</p><p class="muted">${e.status==='live'?`${Math.max(0,Math.round(Date.now()/1000-e.started_at))} seconds elapsed · cutoff ${esc(date(e.deadline))}`:`Last execution: ${esc(date(e.ended_at||e.started_at))}`} · ${esc(e.id.slice(0,8))}</p>${e.messages.length?`<details id="agent-message-${esc(e.id)}"><summary>Latest published explanation</summary>${e.messages.map(m=>`<p class="agent-message">${esc(m)}</p>`).join('')}</details>`:'<p class="muted">No public message has been published for this execution.</p>'}`:'<p class="muted">No execution in this campaign yet.</p>'}</section>`;}).join('')}<details id="agent-history"><summary>All ${agents.executions.length} agent executions</summary>${agents.executions.slice().reverse().map(e=>`<p>${esc(label(e.role))} · ${esc(e.task)} · ${esc(label(e.status))} · ${esc(date(e.started_at))}</p>`).join('')||'<p>No executions yet.</p>'}</details></details>`):card('Research team','<p>Agent telemetry is unavailable. A live count cannot be confirmed.</p>');
 const welcome=unstarted&&!historical?card('What happens after you start',`<ol class="journey"><li><strong>The AI proposes a question.</strong><span>You’ll see what it wants to test and why.</span></li><li><strong>A reviewer checks the method.</strong><span>An accepted method proceeds to a bounded game experiment.</span></li><li><strong>The game runs and evidence appears here.</strong><span>Follow sampled frames, measurements and checkpoints, then read the reviewed conclusion and next decision.</span></li></ol><p class="muted">Keep the workstation awake, plugged in and online, with the dashboard service running. You may close the browser. Stop campaign will be available during execution.</p><p class="launch-note">This is the first extended reliability trial. Short game and recovery checks passed; an eight-hour campaign and a first star have not been demonstrated. Storage or other limits may end it early.</p>`):'';
 const questionFinished=h&&c.jobs.some(j=>j.hypothesis===h.id&&j.result);
 const questionBody=h?`<h2>${esc(h.question)}</h2><details id="method-reasoning"><summary>Why this question and how it will be assessed</summary><p>${esc(h.explanation)}</p><p>${esc(h.alternative)}</p><p>${esc(h.decision)}</p></details>`:'';
 const hypothesis=h?(questionFinished||historical?`<details id="previous-question" class="card"><summary>Previous research question</summary>${questionBody}</details>`:card('Current research question',questionBody)):'';
 const resultEntry=(j,latest=false)=>`<article class="entry"><span class="status">${j.result.reviewed?'Independently reviewed':'Awaiting review'} · ${esc(j.result.validity)}</span><p>${esc((j.result.finding||'No finding recorded.').split(/(?<=[.!?])\s/)[0])}</p><details id="limits-${esc(j.id)}"><summary>Read full finding and recommendation at the time</summary><p>${esc(j.result.finding)}</p><p><strong>Recommendation when recorded:</strong> ${esc(j.result.next_decision)}</p><p>${esc(j.result.limitations)}</p><p class="muted">This is retained evidence. Current campaign status and decisions are shown above.</p></details></article>`;
 const learning=conclusions.length?card('Latest finding',resultEntry(conclusions.at(-1),true)+(conclusions.length>1?`<details id="earlier-findings"><summary>${conclusions.length-1} earlier result${conclusions.length===2?'':'s'}</summary>${conclusions.slice(0,-1).reverse().map(j=>resultEntry(j)).join('')}</details>`:'')):'';
 const usage=(c.ai_executions||[]).reduce((sum,e)=>sum+(e.equivalent_usd||0),0).toFixed(2);
 const running=!unstarted?card(active?'Experiment running':'Latest experiment',`${active?`<p>Completion estimate unavailable until this method is calibrated. Execution cutoff: ${esc(date(active.deadline))}.</p>`:'<p>No game experiment is running.</p>'}${live?.preview?`<figure><img class="game-preview" src="${esc(live.preview)}" alt="Sampled game frame"><figcaption>${active?'Latest sample':'From the previous experiment'} · ${esc(date(sample?.time))}</figcaption></figure>`:''}<details id="execution-details"><summary>Execution and checkpoint details</summary>${work?`<p>${esc(work.phase)} · ${Math.round(work.spent_seconds||0)} seconds recorded</p><p>${work.trials?.[work.trial]?.progress??0} decisions in the latest trial · attempt ${esc(work.attempt)}</p><p>${work.worker_exited?'Process termination confirmed':work.stop_requested?'Stop requested; termination not yet confirmed':'Last observed: '+esc(date(live.observed_at))}</p><p>${Object.values(work.trials||{}).some(t=>t.checkpoint)?'Recovery checkpoint saved':'No committed checkpoint yet'}</p>`:'<p>No runner observation yet.</p>'}${sample?.metrics?`<pre>${esc(JSON.stringify(sample.metrics,null,2))}</pre>`:''}<p class="muted">Exploration and training metrics alone do not establish a star.</p></details>`):'';
 const accountingDetails=`<details id="accounting" class="card"><summary>AI usage · $${usage} reported${(c.ai_executions||[]).some(e=>e.usage==null)?' · incomplete accounting':''}</summary><p>${c.ai_executions?.length||0} of 24 calls used. $${esc(c.policy.ai_equivalent_usd)} accounting target; invocation and time limits remain enforced.</p>${(c.ai_executions||[]).some(e=>e.usage==null)?'<p>Reported usage is a lower bound. Missing receipts do not block work or indicate a live agent.</p>':''}${accounting.map(i=>`<details id="incident-${esc(i.id)}"><summary>Missing usage receipt</summary><p>${esc(brief(i.reason))}</p><p>${esc(i.next_action||'Awaiting a matching receipt')}</p><pre>${esc(JSON.stringify({scope:i.scope,facts:i.facts,evidence:i.evidence},null,2))}</pre></details>`).join('')}</details>`;
 const steering=!historical?`<details id="steering" class="card"><summary>${unstarted?'Optional: add direction before starting':'Change direction for subsequent work'}</summary><form id="steer"><label for="direction">${unstarted?'The prepared objective is sufficient to start. Add a constraint or emphasis only if needed.':'Current bounded work finishes unless you explicitly stop it.'}</label><textarea id="direction" required rows="3" placeholder="Describe your direction"></textarea><button>Record direction</button></form>${c.instructions.map(i=>`<p class="entry">${esc(i.text)}</p>`).join('')}</details>`:'';
 $('#overview').innerHTML=hero+incidentCards+team+welcome+(hypothesis||learning||running?`<div class="grid"><div>${hypothesis}${learning}</div><aside>${running}</aside></div>`:'')+steering+accountingDetails+`<details id="technical" class="card"><summary>Campaign limits, authorization and technical records</summary><p>${esc(c.constraints.join(' · '))}</p>${research?.error?`<details id="interruption-details"><summary>Earlier interruption</summary><pre>${esc(research.error)}</pre></details>`:''}<pre>${esc(JSON.stringify({id:c.id,revision:c.revision,policy:c.policy,reservations:c.reservations,usage:c.usage,jobs:c.jobs,reviews:c.reviews,summary:c.summary},null,2))}</pre></details>`;
 for(const id of open){const element=document.getElementById(id);if(element)element.open=true;}
 if($('#direction')){$('#direction').value=drafts.get(c.id)||'';$('#direction').addEventListener('input',e=>drafts.set(c.id,e.target.value));}
 $('#steer')?.addEventListener('submit',async e=>{e.preventDefault();await command('instruct',{text:$('#direction').value,effect:'future'});});
 $('#stop')?.addEventListener('click',()=>command('stop',{reason:'Human requested stop from campaign dashboard'}));
 $('#start')?.addEventListener('click',()=>command(c.status==='draft'?'authorize':c.status==='authorized'?'start':'renew',{reason:'Human authorized from campaign dashboard'}));
 document.querySelectorAll('.access-check').forEach(b=>b.addEventListener('click',()=>command('decide',{kind:'access_restored',reason:'Human reports subscription access restored; request bounded verification'})));
 $('#resume')?.addEventListener('click',()=>command('resume_session',{reason:'Human resumes the original remaining authorization'}));
 $('#return-current')?.addEventListener('click',()=>{selected=preferred();render();});
}
async function refresh(){
 if(busy)return;
 try{const response=await fetch('/api/campaigns');if(!response.ok)throw Error('Cannot reach research service');payload=await response.json();token=payload.token;$('#connection').textContent='Connected · '+new Date().toLocaleTimeString();if(document.activeElement?.id!=='direction')render();}
 catch(error){$('#connection').textContent='Disconnected · displayed data is cached';$('#message').textContent=error.message;$('#start')?.setAttribute('disabled','');}
}
async function command(operation,inputs={},fresh=false){
 if(busy)return;busy=true;$('#message').textContent='Checking authorization and limits…';
 const c=current(),envelope={request_id:crypto.randomUUID(),operation,...inputs};
 if(!fresh){envelope.campaign=c.id;envelope.expected_revision=c.revision;}
 document.querySelectorAll('#overview button').forEach(b=>b.disabled=true);
 try{const response=await fetch('/api/campaign-command',{method:'POST',headers:{'Content-Type':'application/json','X-Research-Token':token},body:JSON.stringify(envelope)});const result=await response.json();if(!response.ok)throw Error(result.error||'Operation refused');if(fresh){selected=localPrepared=result.campaign;$('#prepare').close();}else if(operation==='instruct'){drafts.delete(c.id);if($('#direction'))$('#direction').value='';}$('#message').textContent=operation==='instruct'?'Direction recorded.':'Request recorded.';}
 catch(error){$('#message').textContent=error.message;}finally{busy=false;await refresh();}
}
$('#new').addEventListener('click',()=>$('#prepare').showModal());$('#cancel').addEventListener('click',()=>$('#prepare').close());
$('#prepare-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);await command('prepare',{objective:f.get('objective'),constraints:f.get('constraints').split('\n').map(s=>s.trim()).filter(Boolean)},true);});
$('#chooser').addEventListener('change',e=>{selected=e.target.value;render();});
refresh();setInterval(refresh,5000);
